"use client";
import { useEffect, useMemo, useState } from "react";
import { createBrowserClient } from "@supabase/ssr";
const money = (n: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(n);
type Store = { id: string; name: string };
export default function Reports() {
  const [stores, setStores] = useState<Store[]>([]), [sid, setSid] = useState(""), [sales, setSales] = useState<any[]>([]), [items, setItems] = useState<any[]>([]), [expenses, setExpenses] = useState<any[]>([]), [waste, setWaste] = useState<any[]>([]), [days, setDays] = useState(30), [loading, setLoading] = useState(true);
  async function load(selectedStore?: string) {
    const supabase = createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
    setLoading(true); const { data: c } = await supabase.auth.getClaims(); const uid = c?.claims?.sub as string | undefined; if (!uid) { location.href = "/login"; return; }
    const { data: m } = await supabase.from("business_members").select("business_id,role").eq("user_id", uid).eq("is_active", true); const o = m?.find(x => String(x.role).toUpperCase() === "OWNER"); if (!o) { setLoading(false); return; }
    const { data: s } = await supabase.from("stores").select("id,name").eq("business_id", o.business_id).eq("is_active", true).order("name"); setStores(s || []); const id = selectedStore || sid || s?.[0]?.id || ""; setSid(id);
    if (!id) { setSales([]); setItems([]); setExpenses([]); setWaste([]); setLoading(false); return; }
    const from = new Date(Date.now() - days * 86400000).toISOString();
    const [{ data: a }, { data: e }, { data: w }] = await Promise.all([
      supabase.from("sales").select("id,transaction_no,total,sold_at,status").eq("store_id", id).gte("sold_at", from).eq("status", "COMPLETED").order("sold_at", { ascending: false }),
      supabase.from("expenses").select("amount,category,spent_at").eq("store_id", id).gte("spent_at", from).order("spent_at", { ascending: false }),
      supabase.from("waste_records").select("quantity,reason,recorded_at,ingredient_id").eq("store_id", id).gte("recorded_at", from).order("recorded_at", { ascending: false })
    ]);
    const saleIds = (a || []).map(x => x.id); const { data: si } = saleIds.length ? await supabase.from("sale_items").select("sale_id,hpp_total,quantity,unit_price").in("sale_id", saleIds) : { data: [] };
    setSales(a || []); setItems(si || []); setExpenses(e || []); setWaste(w || []); setLoading(false);
  }
  useEffect(() => { load(); }, [days]);
  const omzet = useMemo(() => sales.reduce((s, x) => s + Number(x.total || 0), 0), [sales]); const hpp = useMemo(() => items.reduce((s, x) => s + Number(x.hpp_total || 0), 0), [items]); const biaya = useMemo(() => expenses.reduce((s, x) => s + Number(x.amount || 0), 0), [expenses]); const gross = omzet - hpp; const net = gross - biaya;
  return <main style={main}><div style={{maxWidth:1200,margin:"0 auto"}}><header style={head}><div><p style={eyebrow}>BUSINESS REPORTS</p><h1>laporan bisnis</h1><p style={muted}>omzet, HPP, profit, biaya operasional dan aktivitas waste.</p></div><button onClick={() => location.href="/"} style={button}>dashboard</button></header><section style={bar}><select value={sid} onChange={e => load(e.target.value)} style={input}>{stores.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={days} onChange={e => setDays(Number(e.target.value))} style={input}><option value={7}>7 hari</option><option value={30}>30 hari</option><option value={90}>90 hari</option></select></section><section style={stats}><article style={card}><p style={muted}>omzet</p><h2>{money(omzet)}</h2><p style={muted}>{sales.length} transaksi</p></article><article style={card}><p style={muted}>HPP</p><h2>{money(hpp)}</h2><p style={muted}>snapshot recipe saat transaksi</p></article><article style={card}><p style={muted}>gross profit</p><h2>{money(gross)}</h2><p style={muted}>omzet − HPP</p></article><article style={card}><p style={muted}>biaya operasional</p><h2>{money(biaya)}</h2><p style={muted}>{expenses.length} pencatatan</p></article><article style={card}><p style={muted}>net profit</p><h2>{money(net)}</h2><p style={muted}>gross profit − biaya</p></article><article style={card}><p style={muted}>waste records</p><h2>{waste.length}</h2><p style={muted}>periode terpilih</p></article></section><section style={grid}><article style={card}><h2>transaksi terbaru</h2>{loading ? <p style={muted}>memuat...</p> : sales.slice(0,15).map(s => <div style={row} key={s.id}><div><b>{s.transaction_no}</b><p style={muted}>{new Date(s.sold_at).toLocaleString("id-ID")}</p></div><strong>{money(Number(s.total))}</strong></div>)}</article><article style={card}><h2>biaya terbaru</h2>{expenses.slice(0,15).map((e,i) => <div style={row} key={i}><div><b>{e.category}</b><p style={muted}>{new Date(e.spent_at).toLocaleDateString("id-ID")}</p></div><strong>{money(Number(e.amount))}</strong></div>)}</article></section></div></main>;
}
const main={minHeight:"100vh",background:"#090b0d",color:"#f5f1e8",padding:24};const head={display:"flex",justifyContent:"space-between",alignItems:"center",gap:18,marginBottom:22,flexWrap:"wrap"} as const;const eyebrow={color:"#c5a66b",letterSpacing:2,fontSize:11} as const;const muted={color:"#9299a3",fontSize:13} as const;const input={padding:12,borderRadius:10,border:"1px solid #353b43",background:"#0e1013",color:"#f5f1e8"} as const;const button={...input,cursor:"pointer"} as const;const bar={display:"flex",gap:10,marginBottom:16,flexWrap:"wrap"} as const;const stats={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:14,marginBottom:18} as const;const card={padding:20,borderRadius:18,background:"#14171b",border:"1px solid #292e34"} as const;const grid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:16} as const;const row={display:"flex",justifyContent:"space-between",gap:12,padding:"12px 0",borderBottom:"1px solid #292e34"} as const;
