"use client";
import { useEffect, useMemo, useState } from "react";
import { createBrowserClient } from "@supabase/ssr";
const getSupabase=()=>createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
const money=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
const num=(n:number)=>new Intl.NumberFormat("id-ID",{maximumFractionDigits:3}).format(n);
type Store={id:string;name:string}; type Ing={id:string;name:string;current_cost:number;units?:{symbol:string}|{symbol:string}[]|null}; type Row=Ing&{system:number;counted:string;variance:number};
const unitSymbol=(u:Ing["units"])=>Array.isArray(u)?u[0]?.symbol||"":u?.symbol||"";
export default function StockOpname(){const[stores,setStores]=useState<Store[]>([]),[storeId,setStoreId]=useState(""),[ings,setIngs]=useState<Ing[]>([]),[rows,setRows]=useState<Row[]>([]),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState("");
async function load(sid?:string){setErr("");const supabase=getSupabase();const{data:claims}=await supabase.auth.getClaims();const uid=claims?.claims?.sub as string|undefined;if(!uid){location.href="/login";return}const{data:ms}=await supabase.from("business_members").select("business_id,role").eq("user_id",uid).eq("is_active",true);const owner=ms?.find(x=>String(x.role).toUpperCase()==="OWNER");if(!owner){setErr("akses owner diperlukan");return}const{data:ss}=await supabase.from("stores").select("id,name").eq("business_id",owner.business_id).eq("is_active",true).order("name");const{data:ii}=await supabase.from("ingredients").select("id,name,current_cost,units(symbol)").eq("business_id",owner.business_id).eq("is_active",true).order("name");setStores(ss||[]);const ingredients=(ii||[]) as unknown as Ing[];setIngs(ingredients);const id=sid||storeId||ss?.[0]?.id||"";setStoreId(id);if(id){const{data:b}=await supabase.from("inventory_balances").select("ingredient_id,quantity").eq("store_id",id);const bm=new Map((b||[]).map(x=>[x.ingredient_id,Number(x.quantity)]));setRows(ingredients.map(i=>({...i,system:bm.get(i.id)||0,counted:String(bm.get(i.id)||0),variance:0})))}else setRows([])}
useEffect(()=>{load()},[]);const variance=useMemo(()=>rows.reduce((s,r)=>s+(Number(r.counted)-r.system)*Number(r.current_cost||0),0),[rows]);
async function finalize(){if(!storeId||!rows.length)return;setBusy(true);setErr("");setMsg("");const supabase=getSupabase();const{data:claims}=await supabase.auth.getClaims();const uid=claims?.claims?.sub as string;const{data:op,error:e}=await supabase.from("stock_opnames").insert({store_id:storeId,note,created_by:uid}).select("id").single();if(e||!op){setErr(e?.message||"gagal membuat opname");setBusy(false);return}const items=rows.map(r=>({stock_opname_id:op.id,ingredient_id:r.id,system_quantity:r.system,counted_quantity:Number(r.counted),variance:Number(r.counted)-r.system}));const{error:ie}=await supabase.from("stock_opname_items").insert(items);if(ie){setErr(ie.message);setBusy(false);return}const{error:fe}=await supabase.rpc("finalize_stock_opname",{p_opname_id:op.id});if(fe)setErr(fe.message);else{setMsg("stock opname berhasil difinalkan dan stok sudah disesuaikan.");await load(storeId)}setBusy(false)}
return <main style={main}><div style={{maxWidth:1250,margin:"0 auto"}}><header style={head}><div><p style={eyebrow}>INVENTORY CONTROL</p><h1>stock opname</h1><p style={muted}>bandingkan stok sistem dengan hasil hitung fisik lalu finalkan penyesuaian.</p></div><button onClick={()=>location.href="/inventory"} style={button}>inventory</button></header>{msg&&<p style={notice}>{msg}</p>}{err&&<p style={{...notice,color:"#ff8d8d"}}>{err}</p>}<section style={card}><div style={bar}><select value={storeId} onChange={e=>{setStoreId(e.target.value);load(e.target.value)}} style={input}>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input value={note} onChange={e=>setNote(e.target.value)} placeholder="catatan opname (opsional)" style={{...input,flex:1}}/></div><div style={{overflowX:"auto",marginTop:18}}><table style={table}><thead><tr>{["bahan","stok sistem","stok fisik","variance","nilai variance"].map(x=><th key={x} style={th}>{x}</th>)}</tr></thead><tbody>{rows.map(r=>{const v=Number(r.counted)-r.system;return <tr key={r.id}><td style={td}><b>{r.name}</b><span style={muted}> {unitSymbol(r.units)}</span></td><td style={td}>{num(r.system)}</td><td style={td}><input type="number" step="any" min="0" value={r.counted} onChange={e=>setRows(rows.map(x=>x.id===r.id?{...x,counted:e.target.value,variance:Number(e.target.value)-x.system}:x))} style={{...input,width:130}}/></td><td style={{...td,color:v===0?"#9fe2b0":v<0?"#ff8d8d":"#e8bd69"}}>{v>0?"+":""}{num(v)}</td><td style={td}>{money(v*Number(r.current_cost||0))}</td></tr>})}</tbody></table></div><div style={summary}><div><span style={muted}>nilai variance</span><strong style={{fontSize:25,display:"block",marginTop:5}}>{money(variance)}</strong></div><button disabled={busy||!rows.length} onClick={finalize} style={primary}>{busy?"memproses...":"finalkan opname"}</button></div></section></div></main>}
const main={minHeight:"100vh",background:"#090b0d",color:"#f5f1e8",padding:24};const head={display:"flex",justifyContent:"space-between",gap:18,alignItems:"center",marginBottom:24,flexWrap:"wrap"} as const;const eyebrow={color:"#c5a66b",letterSpacing:2,fontSize:12} as const;const muted={color:"#9299a3",fontSize:13} as const;const card={padding:22,borderRadius:18,background:"#14171b",border:"1px solid #292e34"} as const;const input={padding:12,borderRadius:10,border:"1px solid #353b43",background:"#0e1013",color:"#f5f1e8"} as const;const button={...input,cursor:"pointer"} as const;const primary={padding:"12px 17px",border:0,borderRadius:10,background:"#c5a66b",color:"#111",fontWeight:800,cursor:"pointer"} as const;const bar={display:"flex",gap:12,flexWrap:"wrap"} as const;const table={width:"100%",borderCollapse:"collapse"} as const;const th={textAlign:"left",padding:"12px 10px",borderBottom:"1px solid #30353b",color:"#9299a3",fontSize:12} as const;const td={padding:"13px 10px",borderBottom:"1px solid #24282d",fontSize:14} as const;const summary={display:"flex",justifyContent:"space-between",alignItems:"center",gap:15,marginTop:22,paddingTop:18,borderTop:"1px solid #30353b",flexWrap:"wrap"} as const;const notice={padding:12,borderRadius:10,background:"#15181c",border:"1px solid #294334",color:"#9fe2b0",marginBottom:15} as const;
