"use client";

import { FormEvent, useEffect, useState } from "react";
import { createBrowserClient } from "@supabase/ssr";

type Store={id:string;name:string}; type Ingredient={id:string;name:string;unit_id:string;current_cost:number;minimum_stock:number;is_active:boolean;units?:{name:string;symbol:string}|{name:string;symbol:string}[]|null}; type Balance={ingredient_id:string;store_id:string;quantity:number};
const getSupabase=()=>createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
const rupiah=(v:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(v);
function symbol(u:Ingredient["units"]){return Array.isArray(u)?u[0]?.symbol:u?.symbol;}
export default function InventoryPage(){
 const [businessId,setBusinessId]=useState("");const [stores,setStores]=useState<Store[]>([]);const [ingredients,setIngredients]=useState<Ingredient[]>([]);const [balances,setBalances]=useState<Balance[]>([]);const [storeId,setStoreId]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [form,setForm]=useState({ingredientId:"",quantity:"",type:"receipt",note:""});
 async function load(){const supabase=getSupabase();setLoading(true);setError("");const {data:claims}=await supabase.auth.getClaims();const uid=claims?.claims?.sub as string|undefined;if(!uid){window.location.href="/login";return;}const {data:members,error:me}=await supabase.from("business_members").select("business_id,role").eq("user_id",uid).eq("is_active",true);const owner=members?.find(m=>String(m.role).toUpperCase()==="OWNER");if(me||!owner){setError(me?.message||"akun ini belum memiliki akses owner.");setLoading(false);return;}setBusinessId(owner.business_id);const [s,i]=await Promise.all([supabase.from("stores").select("id,name").eq("business_id",owner.business_id).eq("is_active",true).order("name"),supabase.from("ingredients").select("id,name,unit_id,current_cost,minimum_stock,is_active,units(name,symbol)").eq("business_id",owner.business_id).eq("is_active",true).order("name")]);if(s.error)setError(s.error.message);else{setStores(s.data??[]);if(!storeId&&s.data?.[0])setStoreId(s.data[0].id);}if(i.error)setError(i.error.message);else setIngredients((i.data??[]) as Ingredient[]);setLoading(false);}
 async function loadBalances(id:string){if(!id)return;const supabase=getSupabase();const {data,error:err}=await supabase.from("inventory_balances").select("ingredient_id,store_id,quantity").eq("store_id",id);if(err)setError(err.message);else setBalances((data??[]) as Balance[]);}
 useEffect(()=>{load();},[]);useEffect(()=>{loadBalances(storeId);},[storeId]);
 async function adjust(e:FormEvent){e.preventDefault();const supabase=getSupabase();setSaving(true);setError("");setMessage("");const q=Number(form.quantity);if(!storeId||!form.ingredientId||!Number.isFinite(q)||q<=0){setError("outlet, bahan, dan jumlah harus valid.");setSaving(false);return;}if(form.type==="waste"){const {error:err}=await supabase.rpc("record_waste",{p_store_id:storeId,p_ingredient_id:form.ingredientId,p_quantity:q,p_reason:form.note||"waste"});if(err)setError(err.message);else setMessage("waste berhasil dicatat.");}else{const {error:err}=await supabase.rpc("record_goods_receipt",{p_store_id:storeId,p_reference_no:`MANUAL-${Date.now()}`,p_note:form.note||"manual inventory receipt",p_items:[{ingredient_id:form.ingredientId,quantity:q,unit_cost:Number(ingredients.find(i=>i.id===form.ingredientId)?.current_cost||0)}]});if(err)setError(err.message);else setMessage("stok masuk berhasil dicatat.");}await loadBalances(storeId);setSaving(false);}
 const stockValue=balances.reduce((sum,b)=>sum+Number(b.quantity)*(Number(ingredients.find(i=>i.id===b.ingredient_id)?.current_cost)||0),0);const low=balances.filter(b=>{const i=ingredients.find(x=>x.id===b.ingredient_id);return i&&Number(b.quantity)<=Number(i.minimum_stock);}).length;
 return <main style={styles.main}><div style={styles.wrap}><header style={styles.header}><div><small style={styles.gold}>OWNER · INVENTORY CONTROL</small><h1>inventory</h1><p style={styles.muted}>pantau stok, nilai persediaan, dan pergerakan bahan.</p></div><button style={styles.button} onClick={()=>window.location.href="/"}>dashboard</button></header><section style={styles.stats}><div style={styles.card}><span style={styles.muted}>nilai stok</span><b style={styles.metric}>{rupiah(stockValue)}</b></div><div style={styles.card}><span style={styles.muted}>bahan</span><b style={styles.metric}>{ingredients.length}</b></div><div style={styles.card}><span style={styles.muted}>low stock</span><b style={styles.metric}>{low}</b></div></section>{message&&<p style={styles.ok}>{message}</p>}{error&&<p style={styles.err}>{error}</p>}<section style={styles.card}><div style={styles.row}><div><h2>stok outlet</h2><p style={styles.muted}>pilih outlet untuk melihat saldo bahan.</p></div><select value={storeId} onChange={e=>setStoreId(e.target.value)} style={styles.input}><option value="">pilih outlet</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>{loading?<p style={styles.muted}>memuat...</p>:<div style={{overflowX:"auto"}}><table style={styles.table}><thead><tr><th>bahan</th><th>stok</th><th>unit</th><th>cost</th><th>nilai</th></tr></thead><tbody>{ingredients.map(i=>{const b=balances.find(x=>x.ingredient_id===i.id);const q=Number(b?.quantity||0);return <tr key={i.id}><td><b>{i.name}</b></td><td>{q.toLocaleString("id-ID")}</td><td>{symbol(i.units)||"—"}</td><td>{rupiah(Number(i.current_cost))}</td><td>{rupiah(q*Number(i.current_cost))}</td></tr>})}</tbody></table></div>}</section><section style={styles.card}><h2>pergerakan cepat</h2><form onSubmit={adjust} style={styles.form}><select required value={form.ingredientId} onChange={e=>setForm({...form,ingredientId:e.target.value})} style={styles.input}><option value="">pilih bahan</option>{ingredients.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} style={styles.input}><option value="receipt">stok masuk</option><option value="waste">waste</option></select><input required type="number" min="0.01" step="0.01" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})} placeholder="jumlah" style={styles.input}/><input value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="catatan" style={styles.input}/><button disabled={saving||!businessId} style={styles.primary}>{saving?"memproses...":"simpan pergerakan"}</button></form></section></div></main>;
}
const styles={main:{minHeight:"100vh",background:"#090b0d",color:"#f5f1e8",padding:24},wrap:{maxWidth:1220,margin:"0 auto"},header:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,marginBottom:24,flexWrap:"wrap" as const},gold:{color:"#c5a66b",letterSpacing:2,fontSize:11},muted:{color:"#9299a3",fontSize:13},card:{padding:20,borderRadius:18,background:"#14171b",border:"1px solid #292e34",marginBottom:18},stats:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:14},metric:{display:"block",fontSize:28,marginTop:8},row:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap" as const},form:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginTop:14},input:{width:"100%",padding:"12px 13px",borderRadius:10,border:"1px solid #353b43",background:"#0d0f12",color:"#f5f1e8"},button:{padding:"11px 16px",borderRadius:10,border:"1px solid #353b43",background:"#15181c",color:"#f5f1e8"},primary:{padding:"12px 16px",border:0,borderRadius:10,background:"#c5a66b",color:"#111",fontWeight:700},table:{width:"100%",borderCollapse:"collapse" as const,marginTop:14},ok:{color:"#9fe2b0"},err:{color:"#ff8d8d"}} as const;
