"use client";

import { FormEvent, useState } from "react";
import { createClient } from "../../lib/supabase/client";

export default function ManagerLoginPage() {
  const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);
  async function handleSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const supabase=createClient();const{data,error:signInError}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(signInError||!data.user){setError(signInError?.message??"email atau password salah.");setLoading(false);return}const metadata=data.user.user_metadata??{};const fullName=String(metadata.full_name??"").trim();const businessName=String(metadata.business_name??"").trim();const storeName=String(metadata.store_name??"").trim();if(fullName&&businessName&&storeName){const{data:memberships,error:membershipError}=await supabase.from("business_members").select("business_id,role,is_active").eq("user_id",data.user.id).eq("is_active",true);if(!membershipError&&!(memberships??[]).length){const{error:bootstrapError}=await supabase.rpc("bootstrap_manager_account",{p_full_name:fullName,p_business_name:businessName,p_store_name:storeName});if(bootstrapError){await supabase.auth.signOut();setError("akun berhasil login, tetapi setup bisnis gagal. coba lagi.");setLoading(false);return}}}window.location.href="/"}
  return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#f4f7fb",padding:20}}><form onSubmit={handleSubmit} style={{width:"100%",maxWidth:430,padding:30,borderRadius:20,background:"#fff",border:"1px solid #e4e9f0",boxShadow:"0 18px 50px rgba(23,32,51,.08)"}}><p className="brand-kicker">COFFEE SHOP CONTROL</p><h1 style={{margin:"6px 0",fontSize:30}}>manager login</h1><p style={{color:"#6b7485",marginBottom:26}}>masuk ke workspace operasional toko.</p><label style={{display:"block",marginBottom:15}}>email<input className="input" value={email} onChange={e=>setEmail(e.target.value)} type="email" required autoComplete="email" style={{marginTop:7}}/></label><label style={{display:"block",marginBottom:18}}>password<input className="input" value={password} onChange={e=>setPassword(e.target.value)} type="password" required autoComplete="current-password" style={{marginTop:7}}/></label>{error&&<p style={{color:"#c43d3d",marginBottom:15}}>{error}</p>}<button className="primary" disabled={loading}>{loading?"memproses...":"masuk"}</button><a href="/register" style={{display:"block",textAlign:"center",marginTop:16,color:"#b7791f",textDecoration:"none",fontSize:13}}>belum punya akun? daftar akun</a></form></main>;
}
