'use client'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import {createClient} from '../lib/supabase'
type P={id:string;name:string;sku:string|null;selling_price:number};type S={id:string;name:string}
const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n)
export default function Cashier(){const[products,setProducts]=useState<P[]>([]),[stores,setStores]=useState<S[]>([]),[storeId,setStoreId]=useState(''),[q,setQ]=useState(''),[cart,setCart]=useState<{p:P;q:number}[]>([]),[method,setMethod]=useState('CASH'),[paid,setPaid]=useState(''),[err,setErr]=useState(''),[ok,setOk]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false)
 async function load(){const supabase=createClient();setLoading(true);const{data:c}=await supabase.auth.getClaims();const uid=c?.claims?.sub as string|undefined;if(!uid){location.href='/login';return}const{data:m}=await supabase.from('business_members').select('business_id,role').eq('user_id',uid).eq('is_active',true);const member=m?.find(x=>['MANAGER','STAFF','OWNER'].includes(String(x.role).toUpperCase()));if(!member){setErr('akun tidak memiliki akses cashier');setLoading(false);return}const[{data:s},{data:p}]=await Promise.all([supabase.from('stores').select('id,name').eq('business_id',member.business_id).eq('is_active',true).order('name'),supabase.from('products').select('id,name,sku,selling_price').eq('business_id',member.business_id).eq('is_active',true).order('name')]);setStores(s||[]);setProducts((p||[]) as P[]);setStoreId(s?.[0]?.id||'');setLoading(false)}
 useEffect(()=>{load()},[])
 const shown=useMemo(()=>products.filter(p=>!q||p.name.toLowerCase().includes(q.toLowerCase())||(p.sku||'').toLowerCase().includes(q.toLowerCase())),[products,q]);const total=cart.reduce((a,x)=>a+Number(x.p.selling_price)*x.q,0);const change=method==='CASH'?Math.max(0,(Number(paid)||0)-total):0
 function add(p:P){setCart(c=>c.some(x=>x.p.id===p.id)?c.map(x=>x.p.id===p.id?{...x,q:x.q+1}:x):[...c,{p,q:1}])}function adjust(id:string,d:number){setCart(c=>c.map(x=>x.p.id===id?{...x,q:x.q+d}:x).filter(x=>x.q>0))}
 async function save(e:FormEvent){e.preventDefault();setErr('');setOk('');if(!storeId||!cart.length){setErr('pilih outlet dan produk');return}if(method==='CASH'&&(Number(paid)||0)<total){setErr('uang diterima kurang dari total');return}setSaving(true);const supabase=createClient();const{error}=await supabase.rpc('record_sale',{p_store_id:storeId,p_transaction_no:'CSC-'+Date.now(),p_items:cart.map(x=>({product_id:x.p.id,quantity:x.q,unit_price:x.p.selling_price,discount:0})),p_payments:[{method,amount:total}],p_discount:0,p_tax:0});setSaving(false);if(error){setErr(error.message);return}setOk('transaksi berhasil dicatat');setCart([]);setPaid('')}
 if(loading)return <div className="page-wrap"><div className="notice">memuat kasir...</div></div>
 return <div className="page-wrap"><section className="cashier-head"><div><p className="eyebrow">CASHIER · SALES</p><h2>kasir transaksi</h2><p className="muted">input transaksi dipisahkan dari workspace manager dan owner.</p></div><select value={storeId} onChange={e=>setStoreId(e.target.value)} className="select">{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></section>{err&&<div className="notice danger">{err}</div>}{ok&&<div className="notice success">{ok}</div>}<div className="pos-grid"><section className="panel"><div className="search-row"><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="cari nama menu atau SKU..."/></div><div className="product-grid">{shown.map(p=><button type="button" key={p.id} className="product-tile" onClick={()=>add(p)}><small>{p.sku||'MENU'}</small><strong>{p.name}</strong><span>{money(Number(p.selling_price))}</span></button>)}</div>{!shown.length&&<p className="muted empty">belum ada produk yang cocok.</p>}</section><aside className="panel order-panel"><div className="order-title"><div><p className="eyebrow">ORDER</p><h3>keranjang</h3></div><button type="button" className="clear" onClick={()=>setCart([])}>kosongkan</button></div><div className="cart-list">{cart.map(x=><div className="cart-row" key={x.p.id}><div><b>{x.p.name}</b><small>{money(Number(x.p.selling_price))} × {x.q}</small></div><div className="qty"><button type="button" onClick={()=>adjust(x.p.id,-1)}>−</button><span>{x.q}</span><button type="button" onClick={()=>adjust(x.p.id,1)}>+</button></div></div>)}</div><div className="total-row"><span>total</span><strong>{money(total)}</strong></div><form onSubmit={save} className="pay-form"><select className="input" value={method} onChange={e=>setMethod(e.target.value)}><option>CASH</option><option>QRIS</option><option>CARD</option><option>E_WALLET</option><option>BANK_TRANSFER</option><option>OTHER</option></select>{method==='CASH'&&<><input className="input" type="number" min="0" value={paid} onChange={e=>setPaid(e.target.value)} placeholder="uang diterima"/><div className="change"><span>kembalian</span><b>{money(change)}</b></div></>}<button className="primary" disabled={saving||!cart.length}>{saving?'menyimpan...':'simpan transaksi'}</button></form></aside></div></div>}
